%% Import data from ex_rTMS n-back 

% Auto-generated by MATLAB on 2017/08/08 11:31:46

function dataOut = importfile_nback(filename_nback)
%% Import the data
[~, ~, raw] = xlsread(filename_nback);
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[1,3,4,9]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,5,6,7,8,10,11,12,13]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
dataOut = table;

%% Allocate imported array to column variable names
dataOut.text = categorical(stringVectors(:,1));
dataOut.congruent = data(:,1);
dataOut.response = categorical(stringVectors(:,2));
dataOut.corrAns = categorical(stringVectors(:,3));
dataOut.n = data(:,2);
dataOut.respcorr_mean = data(:,3);
dataOut.respcorr_raw = data(:,4);
dataOut.respcorr_std = data(:,5);
dataOut.respkeys_raw = categorical(stringVectors(:,4));
dataOut.resprt_mean = data(:,6);
dataOut.resprt_raw = data(:,7);
dataOut.resprt_std = data(:,8);
dataOut.order = data(:,9);

%% Clear temporary variables
clearvars data raw stringVectors R;